export enum Env {
  DEBUG = 'true',
  HOST = 'HOST',
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  JWT_SECRET = 'JWT_SECRET',
  REFRESH_TOKEN_DURATION = 'REFRESH_TOKEN_DURATION',
  ACCESS_TOKEN_DURATION = 'ACCESS_TOKEN_DURATION',
  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_PASS = 'ADMIN_PASS',
  PG_USER = 'PG_USER',
  PG_PASS = 'PG_PASS',
  PG_DB = 'PG_DB',
  PG_HOST = 'PG_HOST',
  PG_PORT = 'PG_PORT',
}

export enum Roles {
  ADMIN = 'ADMIN',
  NORMAL = 'NORMAL',
}
